name: Kotlin CI with Maven for Spring-7

on:
  push:
  workflow_dispatch:
jobs:
  hystrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fwilhe2/setup-kotlin@main
      - name: Run rdbms tests
        run: mvn -B clean verify --file hystrix/pom.xml
  message-system:
    runs-on: ubuntu-latest
    # Setup Postgres DB for tests
    services:
      rabbitmq:
        image: rabbitmq:3.9-management
        ports:
          - 5672:5672
          - 15672:15672
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      distributor:
        image: shariktlt/sber_kotlin_school_2021_messaging_distributor:1.0.0-SNAPSHOT

    steps:
      - uses: actions/checkout@v2
      - uses: fwilhe2/setup-kotlin@main
      - name: Run spring-security tests
        run: mvn -B clean verify --file message-system/pom.xml
