name: Kotlin CI with Maven for Spring-7

on:
  push:
  workflow_dispatch:
jobs:
  hystrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fwilhe2/setup-kotlin@main
      - name: Run rdbms tests
        run: mvn -B clean verify --file hystrix/pom.xml
